# beacon-bootnode-values.yaml
mode: "bootnode"

initCharts:
  - url: https://github.com/spring-financial-group/ethereum-config-chains
    path: network-configs/private-net/bootnode-metadata
    configName: devnet

devnet:
  enabled: true
  baseUrl: "https://raw.githubusercontent.com/spring-financial-group/ethereum-config-chains/main/network-configs"
  name: "private-net"
  urls:
    depositContractBlock: "https://raw.githubusercontent.com/spring-financial-group/ethereum-config-chains/main/network-configs/private-net/metadata/deposit_contract_block.txt"
    configYaml: "https://raw.githubusercontent.com/spring-financial-group/ethereum-config-chains/main/network-configs/private-net/metadata/config.yaml"
    genesisSsz: "https://raw.githubusercontent.com/spring-financial-group/ethereum-config-chains/main/network-configs/private-net/metadata/genesis.ssz"
    bootstrapNodesYaml: "https://raw.githubusercontent.com/spring-financial-group/ethereum-config-chains/main/network-configs/private-net/bootnode-metadata/bootstrap_nodes.yaml"
    bootstrapNodesTxt: "https://raw.githubusercontent.com/spring-financial-group/ethereum-config-chains/main/network-configs/private-net/bootnode-metadata/bootstrap_nodes.txt"

p2pPort: 9000

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8080"
  prometheus.io/path: "/metrics"

p2pNodePort:
  enabled: false

extraArgs:
  - --testnet-dir=/data/testnet_spec
  - --enr-address=beacon-bootnode-lighthouse.devnet.svc.cluster.local
  - --disable-packet-filter

extraVolumes:
  - name: bootnode-key
    secret:
      secretName: beacon-bootnode-key

extraVolumeMounts:
  - name: bootnode-key
    mountPath: /data/network/key
    subPath: key

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
