apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cm-writer-role
  namespace: devnet
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create", "get", "update"]  # or just ["create"] if that's all you need
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cm-writer-binding
  namespace: devnet
subjects:
  - kind: ServiceAccount
    name: cm-writer-sa
    namespace: devnet
roleRef:
  kind: Role
  name: cm-writer-role