PRESET_BASE: 'mainnet'
CONFIG_NAME: 'testnet' # needs to exist because of Prysm. Otherwise it conflicts with mainnet genesis
TERMINAL_TOTAL_DIFFICULTY: 0
TERMINAL_BLOCK_HASH: 0x0000000000000000000000000000000000000000000000000000000000000000
TERMINAL_BLOCK_HASH_ACTIVATION_EPOCH: 18446744073709551615
MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: 128
MIN_GENESIS_TIME: 1770296789
GENESIS_FORK_VERSION: 0x10000038
GENESIS_DELAY: 0
ALTAIR_FORK_VERSION: 0x20000000
ALTAIR_FORK_EPOCH: 0
BELLATRIX_FORK_VERSION: 0x30000000
BELLATRIX_FORK_EPOCH: 0
CAPELLA_FORK_VERSION: 0x40000000
CAPELLA_FORK_EPOCH: 0
DENEB_FORK_VERSION: 0x50000000
DENEB_FORK_EPOCH: 0
ELECTRA_FORK_VERSION: 0x60000000
ELECTRA_FORK_EPOCH: 1
SECONDS_PER_SLOT: 12
SECONDS_PER_ETH1_BLOCK: 12
ETH1_FOLLOW_DISTANCE: 2048
PROPOSER_REORG_CUTOFF_BPS: 1667
PROPOSER_INCLUSION_LIST_CUTOFF_BPS: 9167
EJECTION_BALANCE: 16000000000
CHURN_LIMIT_QUOTIENT: 65536
PROPOSER_SCORE_BOOST: 40
DEPOSIT_CHAIN_ID: 3151909
DEPOSIT_NETWORK_ID: 3151909
DEPOSIT_CONTRACT_ADDRESS: 0x00000000219ab540356cBB839Cbe05303d7705Fa
PROPOSER_SELECTION_GAP: 2
