PRESET_BASE: minimal
SECONDS_PER_SLOT: 12
GENESIS_DELAY: 120

ALTAIR_FORK_EPOCH: 0
BELLATRIX_FORK_EPOCH: 0
CAPELLA_FORK_EPOCH: 0
DENEB_FORK_EPOCH: 0
ELECTRA_FORK_EPOCH: 0

# critical: allow genesis with a small validator set
MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: 64

